"""Password column name update

Revision ID: 68521a48ce39
Revises: c4e883d781cb
Create Date: 2021-12-04 16:37:20.106271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68521a48ce39'
down_revision = 'c4e883d781cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('master_password', sa.String(), nullable=True))
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(), nullable=True))
    op.drop_column('user', 'master_password')
    # ### end Alembic commands ###
