"""Foreign key added to password table

Revision ID: bdd0551d168e
Revises: 68521a48ce39
Create Date: 2021-12-04 16:53:51.024788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdd0551d168e'
down_revision = '68521a48ce39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('password', sa.Column('user_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'password', 'user', ['user_id'], ['uid'])
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'password', type_='foreignkey')
    op.drop_column('password', 'user_id')
    # ### end Alembic commands ###
